(() => {
  const KEY='multiplication-trainer-v2',TEST_SECONDS=60,TEST_COUNT=20,DEFAULT_STUDENTS=['Luke','Blake','Leo','Brig'];
  const MODEL_URL='https://huggingface.co/onnxmodelzoo/mnist-8/resolve/main/mnist-8.onnx';
  const SKILLS={add:{name:'Addition',symbol:'+'},sub:{name:'Subtraction',symbol:'−'},mul:{name:'Multiplication',symbol:'×'},div:{name:'Division',symbol:'÷'}};
  const $=id=>document.getElementById(id),e={setup:$('setup'),live:$('live'),results:$('results'),student:$('student'),range:$('range'),skills:$('skills'),families:$('families'),start:$('start'),timer:$('timer'),qcount:$('qcount'),progress:$('test-progress'),question:$('question'),recognized:$('recognized'),clear:$('clear'),submit:$('submit-answer'),grade:$('grade-big'),gradeLabel:$('grade-label'),percent:$('percent'),answered:$('answered-stat'),time:$('time-stat'),review:$('review'),again:$('again'),calibrate:$('calibrate'),calibration:$('calibration'),calStatus:$('cal-status'),calDigit:$('cal-digit'),calCanvas:$('cal-canvas'),calClear:$('cal-clear'),calSave:$('cal-save'),calCancel:$('cal-cancel')};
  function uid(){return'u'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
  function blank(name){return{id:uid(),name,mastery:{},history:[],testHistory:[],handwriting:{}}}
  function load(){let x=null;try{x=JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){}if(!x||!Array.isArray(x.students))x={students:[],activeStudent:null};for(const n of DEFAULT_STUDENTS)if(!x.students.some(s=>String(s.name).toLowerCase()===n.toLowerCase()))x.students.push(blank(n));for(const s of x.students){s.mastery=s.mastery||{};s.history=s.history||[];s.testHistory=s.testHistory||[];s.handwriting=s.handwriting||{}}return x}
  let data=load(),sid=data.activeStudent||data.students[0].id,skills=['mul'],families=[3],maxFact=5,questions=[],index=0,answers=[],startedAt=0,timerId=null,ended=false,calIndex=0,modelSession=null,modelState='loading',recognitionSeq=0,lastReading=null,lastSavedTestId=null;
  const canvases=[...document.querySelectorAll('.digit-canvas')],drawings=canvases.map(()=>({strokes:[],current:null})),calDrawing={strokes:[],current:null};
  const P={0:[[[.5,.08],[.3,.1],[.16,.28],[.14,.54],[.2,.8],[.4,.92],[.62,.9],[.8,.72],[.85,.45],[.78,.2],[.62,.09],[.5,.08]]],1:[[[.42,.18],[.52,.08],[.52,.92]]],2:[[[.18,.25],[.32,.1],[.6,.09],[.8,.25],[.75,.43],[.55,.58],[.2,.88],[.82,.88]]],3:[[[.2,.18],[.4,.08],[.68,.14],[.78,.3],[.65,.45],[.48,.5],[.68,.55],[.8,.72],[.67,.9],[.4,.93],[.2,.82]]],4:[[[.68,.92],[.68,.08]],[[.68,.12],[.18,.62],[.86,.62]]],5:[[[.8,.1],[.28,.1],[.23,.46],[.57,.44],[.78,.56],[.8,.76],[.62,.91],[.35,.9],[.18,.78]]],6:[[[.72,.15],[.55,.08],[.34,.18],[.2,.42],[.2,.69],[.35,.88],[.58,.91],[.76,.78],[.74,.58],[.59,.47],[.38,.47],[.23,.58]]],7:[[[.18,.12],[.82,.12],[.62,.42],[.45,.68],[.38,.93]]],8:[[[.5,.49],[.29,.4],[.2,.24],[.3,.09],[.52,.08],[.72,.2],[.68,.38],[.5,.49],[.31,.57],[.21,.74],[.32,.92],[.56,.94],[.77,.8],[.7,.59],[.5,.49]]],9:[[[.76,.52],[.62,.12],[.4,.07],[.21,.22],[.21,.42],[.36,.55],[.6,.54],[.78,.4],[.76,.7],[.64,.9],[.42,.94],[.25,.84]]]};
  function save(){data.activeStudent=sid;try{localStorage.setItem(KEY,JSON.stringify(data))}catch(_){}if(window.MathMasteryAutosave)window.MathMasteryAutosave.queue()}
  function student(){return data.students.find(s=>s.id===sid)||data.students[0]}
  function renderStudents(){e.student.innerHTML='';for(const s of data.students){const o=document.createElement('option');o.value=s.id;o.textContent=s.name;e.student.appendChild(o)}e.student.value=sid;renderCalibrationStatus()}
  function renderPicks(){e.skills.innerHTML='';for(const sk of Object.keys(SKILLS)){const b=document.createElement('button');b.type='button';b.className='test-pick'+(skills.includes(sk)?' on':'');b.textContent=SKILLS[sk].symbol+' '+SKILLS[sk].name;b.onclick=()=>{if(skills.includes(sk)){if(skills.length===1)return;skills=skills.filter(x=>x!==sk)}else skills.push(sk);renderPicks()};e.skills.appendChild(b)}e.families.innerHTML='';for(let n=1;n<=12;n++){const b=document.createElement('button');b.type='button';b.className='test-pick'+(families.includes(n)?' on':'');b.textContent=n;b.onclick=()=>{if(families.includes(n)){if(families.length===1)return;families=families.filter(x=>x!==n)}else families=[...families,n].sort((a,b)=>a-b);renderPicks()};e.families.appendChild(b)}}
  function equation(sk,a,b){if(sk==='mul')return{text:a+' × '+b,answer:a*b};if(sk==='add')return{text:a+' + '+b,answer:a+b};if(sk==='sub')return{text:(a+b)+' − '+a,answer:b};return{text:(a*b)+' ÷ '+a,answer:b}}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function makeQuestions(){const pool=[];for(const sk of skills)for(const a of families)for(let b=0;b<=maxFact;b++)pool.push({sk,a,b,...equation(sk,a,b)});shuffle(pool);const out=[];while(out.length<TEST_COUNT){for(const q of pool){out.push(q);if(out.length===TEST_COUNT)break}shuffle(pool)}return out}
  function fitCanvas(c,fn){const r=c.getBoundingClientRect(),d=Math.max(1,devicePixelRatio||1),w=Math.max(80,Math.round(r.width*d)),h=Math.max(90,Math.round(r.height*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h;fn()}}
  function drawOn(c,d){const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#111';x.lineCap='round';x.lineJoin='round';x.lineWidth=Math.max(6,c.width*.045);for(const st of d.strokes){if(!st.length)continue;x.beginPath();x.moveTo(st[0].x*c.width,st[0].y*c.height);for(let i=1;i<st.length;i++)x.lineTo(st[i].x*c.width,st[i].y*c.height);x.stroke()}}
  const redraw=i=>drawOn(canvases[i],drawings[i]),redrawCal=()=>drawOn(e.calCanvas,calDrawing);
  function point(ev,c){const r=c.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height))}}
  function attach(c,d,onEnd,redrawFn){c.onpointerdown=ev=>{ev.preventDefault();c.setPointerCapture(ev.pointerId);const st=[point(ev,c)];d.strokes.push(st);d.current=st;redrawFn()};c.onpointermove=ev=>{if(!d.current)return;d.current.push(point(ev,c));redrawFn()};const end=()=>{d.current=null;if(onEnd)onEnd()};c.onpointerup=end;c.onpointercancel=end}
  canvases.forEach((c,i)=>attach(c,drawings[i],updateRecognized,()=>redraw(i)));attach(e.calCanvas,calDrawing,null,redrawCal);
  function clearWriting(){for(const d of drawings){d.strokes=[];d.current=null}canvases.forEach((_,i)=>redraw(i));lastReading=null;e.recognized.textContent='I read: —'}
  function clearCal(){calDrawing.strokes=[];calDrawing.current=null;redrawCal()}
  function normalizeStrokes(strokes){const pts=strokes.flat();if(!pts.length)return[];let minX=1,minY=1,maxX=0,maxY=0;for(const p of pts){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}const w=Math.max(.03,maxX-minX),h=Math.max(.03,maxY-minY),scale=.72/Math.max(w,h),ox=.5-(minX+maxX)*scale/2,oy=.5-(minY+maxY)*scale/2;return strokes.map(st=>st.map(p=>({x:p.x*scale+ox,y:p.y*scale+oy})))}
  function rasterArray(strokes,size=28){const c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');x.fillStyle='#000';x.fillRect(0,0,size,size);x.strokeStyle='#fff';x.lineCap='round';x.lineJoin='round';x.lineWidth=2.6;for(const st of normalizeStrokes(strokes)){if(!st.length)continue;x.beginPath();x.moveTo(st[0].x*size,st[0].y*size);for(let i=1;i<st.length;i++)x.lineTo(st[i].x*size,st[i].y*size);x.stroke()}const im=x.getImageData(0,0,size,size).data,out=new Float32Array(size*size);for(let i=0;i<out.length;i++)out[i]=im[i*4]/255;return out}
  function rasterPts(strokes){const a=rasterArray(strokes),out=[];for(let i=0;i<a.length;i++)if(a[i]>.15)out.push([i%28,Math.floor(i/28)]);return out}
  function dist(a,b){if(!a.length||!b.length)return 999;let s=0;for(const p of a){let best=999;for(const q of b){const dx=p[0]-q[0],dy=p[1]-q[1],v=dx*dx+dy*dy;if(v<best)best=v}s+=best}return s/a.length}
  function heuristicScores(strokes){const ink=rasterPts(strokes),hw=student().handwriting||{},scores=Array(10).fill(99);for(let d=0;d<10;d++){for(const sample of [...(hw[d]||[]),P[d]]){const sc=(dist(ink,rasterPts(sample))+dist(rasterPts(sample),ink))/46+(sample===P[d]?.55:0);scores[d]=Math.min(scores[d],sc)}}const inv=scores.map(v=>Math.exp(-Math.min(12,v*2.4))),sum=inv.reduce((a,b)=>a+b,0)||1;return inv.map(v=>v/sum)}
  function softmax(a){const m=Math.max(...a),x=a.map(v=>Math.exp(v-m)),s=x.reduce((p,q)=>p+q,0)||1;return x.map(v=>v/s)}
  async function loadModel(){if(!window.ort){modelState='unavailable';renderCalibrationStatus();return}try{ort.env.wasm.numThreads=1;modelSession=await ort.InferenceSession.create(MODEL_URL,{executionProviders:['wasm']});modelState='ready'}catch(err){console.warn('MNIST model unavailable; using personalized fallback',err);modelState='unavailable'}renderCalibrationStatus()}
  async function digitPrediction(strokes){if(!strokes.flat().length)return null;const hs=heuristicScores(strokes);let probs=hs,neural=false;if(modelSession){try{const input=new ort.Tensor('float32',rasterArray(strokes),[1,1,28,28]),out=await modelSession.run({Input3:input}),tensor=out[modelSession.outputNames[0]],np=softmax(Array.from(tensor.data));probs=np.map((p,i)=>p*.78+hs[i]*.22);neural=true}catch(err){console.warn('MNIST inference failed',err)}}let best=0,second=1;if(probs[1]>probs[0]){best=1;second=0}for(let i=2;i<10;i++){if(probs[i]>probs[best]){second=best;best=i}else if(probs[i]>probs[second])second=i}return{digit:best,confidence:probs[best],margin:probs[best]-probs[second],neural}}
  async function readAnswer(){const preds=[];for(const d of drawings)preds.push(await digitPrediction(d.strokes));let str='',confidence=1,uncertain=false,usedNeural=false;for(const p of preds){if(!p){if(str)break;continue}str+=p.digit;confidence=Math.min(confidence,p.confidence);uncertain=uncertain||p.confidence<.56||p.margin<.13;usedNeural=usedNeural||p.neural}return str?{value:Number(str),confidence,uncertain,usedNeural}:null}
  async function updateRecognized(){const seq=++recognitionSeq;e.recognized.textContent='Reading…';const r=await readAnswer();if(seq!==recognitionSeq)return;lastReading=r;e.recognized.textContent=r?'I read: '+r.value+(r.uncertain?' · low confidence — check it':''):'I read: —'}
  function renderCalibrationStatus(){const hw=student().handwriting||{},covered=Array.from({length:10},(_,d)=>(hw[d]||[]).length>0).filter(Boolean).length,engine=modelState==='ready'?'Neural digit model ready':modelState==='loading'?'Loading neural digit model…':'Neural model unavailable; personalized fallback active';e.calStatus.textContent=engine+' · personal samples: '+covered+'/10 digits.'}
  function startCalibration(){calIndex=0;e.calibration.style.display='block';e.calibrate.style.display='none';e.calDigit.textContent='0';clearCal();setTimeout(()=>fitCanvas(e.calCanvas,redrawCal),0)}
  function saveCalibration(){if(!calDrawing.strokes.flat().length)return;const hw=student().handwriting||(student().handwriting={}),sample=normalizeStrokes(calDrawing.strokes);hw[calIndex]=hw[calIndex]||[];hw[calIndex].push(sample);if(hw[calIndex].length>8)hw[calIndex]=hw[calIndex].slice(-8);save();calIndex++;if(calIndex>9){e.calibration.style.display='none';e.calibrate.style.display='inline-block';renderCalibrationStatus();return}e.calDigit.textContent=String(calIndex);clearCal()}
  function cancelCalibration(){e.calibration.style.display='none';e.calibrate.style.display='inline-block';clearCal();renderCalibrationStatus()}
  function showQuestion(){if(index>=TEST_COUNT){finish(false);return}e.question.textContent=questions[index].text;e.qcount.textContent='Question '+(index+1)+' of '+TEST_COUNT;e.progress.style.width=index/TEST_COUNT*100+'%';clearWriting()}
  function startTest(){maxFact=Number(e.range.value)||5;questions=makeQuestions();answers=[];index=0;ended=false;lastSavedTestId=null;startedAt=Date.now();e.setup.style.display='none';e.results.style.display='none';e.live.style.display='block';canvases.forEach((c,i)=>fitCanvas(c,()=>redraw(i)));showQuestion();tick();timerId=setInterval(tick,200)}
  function tick(){if(ended)return;const elapsed=(Date.now()-startedAt)/1000,remain=Math.max(0,TEST_SECONDS-elapsed);e.timer.textContent='0:'+String(Math.ceil(remain)).padStart(2,'0');e.timer.classList.toggle('low',remain<=10);if(remain<=0)finish(true)}
  async function submitAnswer(){if(ended)return;e.submit.disabled=true;const r=await readAnswer();e.submit.disabled=false;if(!r){e.recognized.textContent='Write an answer first.';return}answers.push({q:questions[index],read:r.value,correct:r.value===questions[index].answer,confidence:r.confidence,uncertain:r.uncertain});index++;showQuestion()}
  function recalc(){for(const a of answers)a.correct=a.read===a.q.answer}
  function persistResult(timedOut,elapsed){recalc();const correct=answers.filter(a=>a.correct).length,answered=answers.filter(a=>a.read!==null).length,pct=Math.round(correct/TEST_COUNT*100),id=lastSavedTestId||uid();const item={id,at:new Date().toISOString(),type:'test',skills:[...skills],skillsLabel:'60-second test · '+skills.map(sk=>SKILLS[sk].name).join(' + '),families:[...families],maxFact,questions:TEST_COUNT,answered,correct,percent:pct,seconds:timedOut?60:Number(elapsed.toFixed(1)),score:correct*5,recognizer:modelState==='ready'?'onnx-mnist+personal':'personal-fallback'};const th=student().testHistory,hh=student().history,ti=th.findIndex(x=>x.id===id),hi=hh.findIndex(x=>x.id===id);if(ti>=0)th[ti]=item;else th.push(item);if(hi>=0)hh[hi]=item;else hh.push(item);if(th.length>100)student().testHistory=th.slice(-100);if(hh.length>160)student().history=hh.slice(-160);lastSavedTestId=id;save();return item}
  function renderResults(timedOut,elapsed){recalc();const correct=answers.filter(a=>a.correct).length,answered=answers.filter(a=>a.read!==null).length,pct=Math.round(correct/TEST_COUNT*100);e.grade.textContent=correct+'/'+TEST_COUNT;e.gradeLabel.textContent=pct>=90?'Excellent fluency!':pct>=75?'Strong work!':pct>=50?'Good effort — keep building.':'Keep practicing — speed will come.';e.percent.textContent=pct+'% correct';e.answered.textContent=answered+' answered';e.time.textContent=(timedOut?'60.0':elapsed.toFixed(1))+' sec';e.review.innerHTML='';answers.forEach((a,i)=>{const d=document.createElement('div');d.className='review-row';const conf=a.read===null?'':(a.uncertain?' · recognition uncertain':'');d.innerHTML='<div class="review-q">'+a.q.text+' = '+a.q.answer+'</div><div class="review-a">Read: '+(a.read===null?'blank':a.read)+conf+'</div><div class="right '+(a.correct?'':'wrong-text')+'">'+(a.correct?'✓':'✕')+'</div>';if(!a.correct&&a.read!==null){const b=document.createElement('button');b.type='button';b.className='secondary-btn';b.textContent='Fix reading';b.onclick=()=>{const v=prompt('What number was actually written?',String(a.read));if(v===null)return;const n=Number(v.trim());if(!Number.isInteger(n)||n<0||n>999)return;a.read=n;a.uncertain=false;persistResult(timedOut,elapsed);renderResults(timedOut,elapsed)};d.appendChild(b)}e.review.appendChild(d)})}
  function finish(timedOut){if(ended)return;ended=true;if(timerId)clearInterval(timerId);timerId=null;const elapsed=Math.min(TEST_SECONDS,(Date.now()-startedAt)/1000);while(answers.length<TEST_COUNT){const q=questions[answers.length];answers.push({q,read:null,correct:false,confidence:0,uncertain:true})}e.live.style.display='none';e.results.style.display='block';persistResult(timedOut,elapsed);renderResults(timedOut,elapsed)}
  e.student.onchange=()=>{sid=e.student.value;save();renderCalibrationStatus()};e.range.onchange=()=>{maxFact=Number(e.range.value)||5};e.start.onclick=startTest;e.clear.onclick=clearWriting;e.submit.onclick=submitAnswer;e.again.onclick=()=>{e.results.style.display='none';e.setup.style.display='block';renderCalibrationStatus()};e.calibrate.onclick=startCalibration;e.calClear.onclick=clearCal;e.calSave.onclick=saveCalibration;e.calCancel.onclick=cancelCalibration;addEventListener('resize',()=>{if(e.live.style.display==='block')canvases.forEach((c,i)=>fitCanvas(c,()=>redraw(i)));if(e.calibration.style.display==='block')fitCanvas(e.calCanvas,redrawCal)});
  renderStudents();renderPicks();save();renderCalibrationStatus();loadModel();
})();