(() => {
  const $=id=>document.getElementById(id);
  const MODE=document.body.dataset.mode||'mul';
  const SKILLS={mul:{name:'Multiplication',symbol:'×'},add:{name:'Addition',symbol:'+'},sub:{name:'Subtraction',symbol:'−'},div:{name:'Division',symbol:'÷'}};
  const KEY='multiplication-trainer-v2';
  const SESSION_MAX=20;
  const e={student:$('student'),addStudent:$('add-student'),familyPicks:$('family-picks'),familyNote:$('family-note'),skillPicks:$('skill-picks'),range:$('range'),rangeNote:$('range-note'),brand:$('brand'),streak:$('streak'),score:$('score'),bar:$('bar'),play:$('play'),finish:$('finish'),finishText:$('finish-text'),mode:$('mode'),q:$('question'),answers:$('answers'),form:$('type-form'),input:$('type-input'),feedback:$('feedback'),explain:$('explain'),facts:$('facts'),masteryTitle:$('mastery-title'),masterySummary:$('mastery-summary'),overallSummary:$('overall-summary'),historyList:$('history-list'),hint:$('hint'),restart:$('restart'),again:$('again')};
  function uid(){return 'u'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
  function blankStudent(name){return {id:uid(),name,mastery:{},history:[]}}
  function load(){
    let x=null;try{const raw=localStorage.getItem(KEY);if(raw)x=JSON.parse(raw)}catch(_){ }
    if(!x||!Array.isArray(x.students)||!x.students.length)x={students:[blankStudent('Luke'),blankStudent('Blake')],activeStudent:null};
    for(const st of x.students){st.mastery=st.mastery||{};st.history=st.history||[];for(const k of Object.keys(st.mastery)){const m=k.match(/^(\d+)x(\d+)$/);if(m){const nk='mul:'+m[1]+':'+m[2];if(st.mastery[nk]==null)st.mastery[nk]=st.mastery[k]}}}
    return x;
  }
  let data=load(),studentId=data.activeStudent||data.students[0].id,families=[3],maxFact=5,skills=MODE==='mixed'?['mul','add']: [MODE],s;
  function save(){data.activeStudent=studentId;try{localStorage.setItem(KEY,JSON.stringify(data))}catch(_){}}
  function student(){return data.students.find(x=>x.id===studentId)||data.students[0]}
  function key(skill,a,b){return skill+':'+a+':'+b}
  function getSaved(skill,a,b){return Math.max(0,Math.min(3,Number(student().mastery[key(skill,a,b)])||0))}
  function setSaved(skill,a,b,v){student().mastery[key(skill,a,b)]=Math.max(0,Math.min(3,v));save()}
  function selectedFacts(){const out=[];for(const skill of skills)for(const a of families)for(let b=0;b<=maxFact;b++)out.push([skill,a,b]);return out}
  function totalFacts(){return selectedFacts().length}
  function knownCount(){return selectedFacts().filter(([sk,a,b])=>(s.mastery[key(sk,a,b)]||0)>=3).length}
  function allStrong(){return totalFacts()>0&&knownCount()===totalFacts()}
  function renderStudents(){e.student.innerHTML='';for(const x of data.students){const o=document.createElement('option');o.value=x.id;o.textContent=x.name;e.student.appendChild(o)}e.student.value=studentId}
  function renderFamilies(){e.familyPicks.innerHTML='';for(let a=1;a<=12;a++){const b=document.createElement('button');b.type='button';b.className='pick'+(families.includes(a)?' on':'');b.textContent=a;b.setAttribute('aria-pressed',families.includes(a));b.addEventListener('click',()=>toggleFamily(a));e.familyPicks.appendChild(b)}e.familyNote.textContent=families.length===1?'Using '+families[0]:'Using '+families.join(', ')}
  function renderSkills(){if(!e.skillPicks)return;if(MODE!=='mixed'){e.skillPicks.style.display='none';return}e.skillPicks.innerHTML='';for(const sk of Object.keys(SKILLS)){const b=document.createElement('button');b.type='button';b.className='pick'+(skills.includes(sk)?' on':'');b.textContent=SKILLS[sk].symbol+' '+SKILLS[sk].name;b.setAttribute('aria-pressed',skills.includes(sk));b.addEventListener('click',()=>toggleSkill(sk));e.skillPicks.appendChild(b)}}
  function titleText(){if(MODE==='mixed')return 'Mixed Skills';return SKILLS[MODE].name+' Trainer'}
  function labels(){e.brand.textContent=titleText();e.rangeNote.textContent='Facts 0–'+maxFact+' · '+totalFacts()+' selected facts · 20-question sessions';renderFamilies();renderSkills()}
  function fresh(){const mastery={};for(const [sk,a,b] of selectedFacts())mastery[key(sk,a,b)]=getSaved(sk,a,b);return {round:0,score:0,streak:0,current:null,locked:false,mastery,misses:{},recent:[],type:'choice',startKnown:Object.values(mastery).filter(v=>v>=3).length}}
  function init(){s=fresh();labels();e.play.style.display='block';e.finish.style.display='none';stats();renderMastery();renderHistory();updateBar();next()}
  function toggleFamily(a){if(families.includes(a)){if(families.length===1)return;families=families.filter(x=>x!==a)}else families=[...families,a].sort((x,y)=>x-y);init()}
  function toggleSkill(sk){if(skills.includes(sk)){if(skills.length===1)return;skills=skills.filter(x=>x!==sk)}else skills=[...skills,sk];init()}
  function pick(){const pool=[];for(const f of selectedFacts()){const [sk,a,b]=f,k=key(sk,a,b),m=s.mastery[k]||0;if(m>=3)continue;let w=5+(s.misses[k]||0)*4+(3-m)*2;if(s.recent.slice(-2).includes(k))w=Math.max(1,Math.floor(w/4));for(let i=0;i<w;i++)pool.push(f)}if(pool.length)return pool[Math.floor(Math.random()*pool.length)];const all=selectedFacts();return all[Math.floor(Math.random()*all.length)]}
  function equation(sk,a,b){if(sk==='mul')return {text:a+' × '+b,answer:a*b,explain:a+' × '+b+' = '+(a*b)};if(sk==='add')return {text:a+' + '+b,answer:a+b,explain:a+' + '+b+' = '+(a+b)};if(sk==='sub')return {text:(a+b)+' − '+a,answer:b,explain:(a+b)+' − '+a+' = '+b};return {text:(a*b)+' ÷ '+a,answer:b,explain:(a*b)+' ÷ '+a+' = '+b}}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function options(correct,a){const set=new Set([correct]);const cand=[correct+1,correct-1,correct+2,correct-2,correct+a,correct-a,correct+3,correct-3].filter(x=>x>=0&&x<=144&&x!==correct);shuffle(cand);for(const x of cand)if(set.size<4)set.add(x);while(set.size<4)set.add(Math.floor(Math.random()*Math.max(20,correct+10)));return shuffle([...set])}
  function next(){if(s.round>=SESSION_MAX){done();return}if(allStrong()&&s.round>0){done();return}s.locked=false;s.current=pick();const [sk,a,b]=s.current,k=key(sk,a,b);s.recent.push(k);s.round++;const q=equation(sk,a,b);e.q.textContent=q.text;const r=s.round;s.type=(r<=4||r%3===0)?'choice':'type';const stage=r<=5?'Build confidence':r<=12?'Practice':'Recall';e.mode.textContent=(MODE==='mixed'?SKILLS[sk].name+' · ':'')+stage+' · '+(s.type==='type'?'TYPE IT':'CHOOSE IT');e.feedback.textContent=s.type==='type'?'Type the answer.':'Choose the answer.';e.explain.textContent='';questionUI(q.answer,a);updateBar()}
  function questionUI(correct,a){e.answers.innerHTML='';if(s.type==='type'){e.answers.style.display='none';e.form.style.display='flex';e.input.value='';setTimeout(()=>e.input.focus(),0)}else{e.form.style.display='none';e.answers.style.display='grid';for(const v of options(correct,a)){const b=document.createElement('button');b.type='button';b.className='answer';b.textContent=v;b.addEventListener('click',()=>answer(v,b));e.answers.appendChild(b)}}}
  function answer(v,b){if(s.locked)return;v=Number(v);if(!Number.isFinite(v))return;s.locked=true;const [sk,a,n]=s.current,k=key(sk,a,n),q=equation(sk,a,n),c=q.answer;if(v===c){if(b)b.classList.add('correct');s.streak++;s.score+=(s.type==='type'?15:10)+Math.min(10,s.streak);s.mastery[k]=Math.min(3,(s.mastery[k]||0)+1);setSaved(sk,a,n,s.mastery[k]);e.feedback.textContent=s.streak>=5?'🔥 '+s.streak+' in a row!':'Yes! '+c+' is right!';e.explain.textContent=q.explain;setTimeout(next,800)}else{if(b)b.classList.add('wrong');s.streak=0;s.misses[k]=(s.misses[k]||0)+1;s.mastery[k]=Math.max(0,(s.mastery[k]||0)-1);setSaved(sk,a,n,s.mastery[k]);if(s.type==='choice')for(const x of e.answers.querySelectorAll('button'))if(Number(x.textContent)===c)x.classList.add('correct');e.feedback.textContent='Almost — the answer is '+c+'.';e.explain.textContent=q.explain+' · You’ll see this one again.';setTimeout(next,1300)}stats();renderMastery();renderHistory();updateBar()}
  function stats(){e.streak.textContent=s.streak;e.score.textContent=s.score}
  function updateBar(){e.bar.style.width=(knownCount()/Math.max(1,totalFacts())*100)+'%'}
  function factLabel(sk,a,b){return equation(sk,a,b).text}
  function renderMastery(){e.facts.innerHTML='';const strong=selectedFacts().filter(([sk,a,b])=>getSaved(sk,a,b)>=3).length;e.masteryTitle.textContent=student().name+' · Saved mastery';e.masterySummary.textContent=strong+' of '+totalFacts()+' selected facts are strong. Mastery carries across sessions and pages.';for(const [sk,a,b] of selectedFacts()){const m=getSaved(sk,a,b),d=document.createElement('div');d.className='fact'+(m>=3?' known':m>0?' learning':'');d.innerHTML='<span>'+factLabel(sk,a,b)+'</span><small>'+['new','building 1/3','building 2/3','strong'][m]+'</small>';e.facts.appendChild(d)}}
  function skillStrong(sk){let c=0;for(let a=1;a<=12;a++)for(let b=0;b<=12;b++)if(getSaved(sk,a,b)>=3)c++;return c}
  function renderHistory(){e.overallSummary.textContent='Overall strong facts — × '+skillStrong('mul')+' · + '+skillStrong('add')+' · − '+skillStrong('sub')+' · ÷ '+skillStrong('div')+'. Saved on this device.';e.historyList.innerHTML='';const h=student().history||[];if(!h.length){e.historyList.innerHTML='<div class="empty">No completed sessions yet.</div>';return}for(const item of h.slice(-8).reverse()){const d=document.createElement('div');d.className='history-item';const date=new Date(item.at);const skillLabel=item.skillsLabel||item.tablesLabel||'Multiplication';d.innerHTML='<div><div class="history-main">'+escapeHtml(skillLabel)+'</div><div class="history-sub">'+date.toLocaleDateString()+' · '+(item.strong??0)+' of '+(item.total??0)+' strong · '+(item.questions??0)+' questions</div></div><div class="pill">⭐ '+(item.score??0)+'</div>';e.historyList.appendChild(d)}}
  function escapeHtml(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function hint(){if(s.locked||!s.current)return;const [sk,a,b]=s.current,q=equation(sk,a,b);if(sk==='mul')e.feedback.textContent='Think of '+b+' groups of '+a+'.';else if(sk==='div')e.feedback.textContent='Think: what number times '+a+' equals '+(a*b)+'?';else if(sk==='add')e.feedback.textContent='Start at '+a+' and count up '+b+'.';else e.feedback.textContent='Think of the matching addition fact: '+b+' + '+a+' = '+(a+b)+'.';e.explain.textContent=q.explain}
  function done(){const known=knownCount();updateBar();e.play.style.display='none';e.finish.style.display='block';e.finishText.textContent='You scored '+s.score+' points and finished with '+known+' of '+totalFacts()+' selected facts strong in '+s.round+' questions. Progress is saved for next time.';student().history=student().history||[];student().history.push({at:new Date().toISOString(),mode:MODE,skills:[...skills],skillsLabel:skills.map(sk=>SKILLS[sk].name).join(' + '),families:[...families],maxFact,strong:known,total:totalFacts(),questions:s.round,score:s.score});if(student().history.length>120)student().history=student().history.slice(-120);save();renderHistory();renderMastery()}
  e.form.addEventListener('submit',ev=>{ev.preventDefault();if(s.locked)return;const raw=e.input.value.trim();if(raw===''){e.feedback.textContent='Type an answer first.';return}const v=Number(raw);if(!Number.isFinite(v)||v<0||v>144){e.feedback.textContent='Enter a number from 0 to 144.';return}answer(v,null)});
  e.student.addEventListener('change',()=>{studentId=e.student.value;save();init()});
  e.addStudent.addEventListener('click',()=>{const name=prompt('Student name:');if(!name||!name.trim())return;const x=blankStudent(name.trim().slice(0,30));data.students.push(x);studentId=x.id;save();renderStudents();init()});
  e.range.addEventListener('change',()=>{const n=Number(e.range.value);maxFact=[5,10,12].includes(n)?n:5;init()});
  e.hint.addEventListener('click',hint);e.restart.addEventListener('click',init);e.again.addEventListener('click',init);
  renderStudents();init();
})();